twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'bootstrap_5_layout.html.twig' ]
    globals:
        option_service: '@App\Services\OptionsService'
        catalogue_services: '@App\Services\CatalogueServices'
        client_services: '@App\Services\ClientsService'
when@test:
    twig:
        strict_variables: true
